#!/usr/bin/env ruby
require 'captain_hoog'
cucumber_hoogfile = File.expand_path(File.join(File.dirname(__FILE__),
                                               "config", "cucumber"))

hoog_config = CaptainHoog::Hoogfile.config(cucumber_hoogfile)

plugin_list = CaptainHoog::PluginList.new('pre-commit',
                                          config: hoog_config)
# Adjust settings
CaptainHoog::PreGit.configure do |config|
  config.plugins_dir      = hoog_config['plugins_dir']
  config.project_dir      = hoog_config['project_dir']
  config.plugins_conf     = hoog_config.plugins_env
end

CaptainHoog::PreGit.run(plugins_list: plugin_list)
