#!/usr/bin/env ruby
require 'captain_hoog'

plugins_path = File.expand_path(File.join(File.dirname(__FILE__),
                                          "plugins",
                                          "test_plugins",
                                          "failing"))

hoog_config = {
  'exclude' => [],
  'plugins_dir' => plugins_path,
  'project_dir' => 'with_git',
  'pre-commit' => ['foo']
}

plugin_list = CaptainHoog::PluginList.new('pre-commit',
                                          config: hoog_config)

# Adjust settings
CaptainHoog::PreGit.configure do |config|
  config.plugins_dir      = hoog_config['plugins_dir']
  config.project_dir      = hoog_config['project_dir']
end

CaptainHoog::PreGit.run(plugins_list: plugin_list)
