#!/usr/bin/env ruby
require 'captain_hoog'

plugins_path = File.expand_path(File.join(File.dirname(__FILE__),
                                          "plugins",
                                          "test_plugins",
                                          "failing"))

CaptainHoog::PreGit.plugins_dir = plugins_path
CaptainHoog::PreGit.project_dir = 'with_git'
CaptainHoog::PreGit.run
